<?php

return [
    'definitions' => [
        \domain\Applications\Repository\ApplicationsRepositoryInterface::class => \infrastructure\Applications\Repository\ApplicationsRepository::class,
        \domain\Applications\DataMapper\ApplicationsDataMapperInterface::class => \infrastructure\Applications\DataMapper\ApplicationsDataMapper::class,
        \application\Applications\Form\ApplicationsFormModelProviderInterface::class => \infrastructure\Applications\Form\ApplicationsFormModelProvider::class,
        \domain\Gaz\Repository\GazRepositoryInterface::class => \infrastructure\Gaz\Repository\GazRepository::class,
        \domain\Gaz\DataMapper\GazDataMapperInterface::class => \infrastructure\Gaz\DataMapper\GazDataMapper::class,
        \application\Gaz\Form\GazFormModelProviderInterface::class => \infrastructure\Gaz\Form\GazFormModelProvider::class,
        \domain\Manufacture\Repository\ManufactureRepositoryInterface::class => \infrastructure\Manufacture\Repository\ManufactureRepository::class,
        \domain\Manufacture\DataMapper\ManufactureDataMapperInterface::class => \infrastructure\Manufacture\DataMapper\ManufactureDataMapper::class,
        \application\Manufacture\Form\ManufactureFormModelProviderInterface::class => \infrastructure\Manufacture\Form\ManufactureFormModelProvider::class,
        \domain\News\Repository\NewsRepositoryInterface::class => \infrastructure\News\Repository\NewsRepository::class,
        \domain\News\DataMapper\NewsDataMapperInterface::class => \infrastructure\News\DataMapper\NewsDataMapper::class,
        \application\News\Form\NewsFormModelProviderInterface::class => \infrastructure\News\Form\NewsFormModelProvider::class,
        \domain\User\Repository\UserRepositoryInterface::class => \infrastructure\User\Repository\UserRepository::class,
        \domain\User\DataMapper\UserDataMapperInterface::class => \infrastructure\User\DataMapper\UserDataMapper::class,
        \application\User\Form\UserFormModelProviderInterface::class => \infrastructure\User\Form\UserFormModelProvider::class,
        \domain\Order\Repository\OrderRepositoryInterface::class => \infrastructure\Order\Repository\OrderRepository::class,
        \domain\Order\DataMapper\OrderDataMapperInterface::class => \infrastructure\Order\DataMapper\OrderDataMapper::class,
        \application\Order\Form\OrderFormModelProviderInterface::class => \infrastructure\Order\Form\OrderFormModelProvider::class,
        \domain\OrderProduct\Repository\OrderProductRepositoryInterface::class => \infrastructure\OrderProduct\Repository\OrderProductRepository::class,
        \domain\OrderProduct\DataMapper\OrderProductDataMapperInterface::class => \infrastructure\OrderProduct\DataMapper\OrderProductDataMapper::class,
        \domain\Page\Repository\PageRepositoryInterface::class => \infrastructure\Page\Repository\PageRepository::class,
        \domain\Page\DataMapper\PageDataMapperInterface::class => \infrastructure\Page\DataMapper\PageDataMapper::class,
        \application\Page\Form\PageFormModelProviderInterface::class => \infrastructure\Page\Form\PageFormModelProvider::class,
        \domain\Product\Repository\ProductRepositoryInterface::class => \infrastructure\Product\Repository\ProductRepository::class,
        \domain\Product\DataMapper\ProductDataMapperInterface::class => \infrastructure\Product\DataMapper\ProductDataMapper::class,
        \application\Product\Form\ProductFormModelProviderInterface::class => \infrastructure\Product\Form\ProductFormModelProvider::class,
        \application\Product\Port\ProductFileManagerInterface::class => \infrastructure\Product\Service\ProductFileManager::class,
        \application\Product\Port\ProductRelationManagerInterface::class => \infrastructure\Product\Service\ProductRelationManager::class,
        \application\Product\Port\SensorsImporterInterface::class => \infrastructure\Product\Service\SensorsImporter::class,
        \domain\Redirect\Repository\RedirectRepositoryInterface::class => \infrastructure\Redirect\Repository\RedirectRepository::class,
        \domain\Redirect\DataMapper\RedirectDataMapperInterface::class => \infrastructure\Redirect\DataMapper\RedirectDataMapper::class,
        \application\Redirect\Form\RedirectFormModelProviderInterface::class => \infrastructure\Redirect\Form\RedirectFormModelProvider::class,
        \domain\Seo\Repository\SeoRepositoryInterface::class => \infrastructure\Seo\Repository\SeoRepository::class,
        \domain\Seo\DataMapper\SeoDataMapperInterface::class => \infrastructure\Seo\DataMapper\SeoDataMapper::class,
        \application\Seo\Form\SeoFormModelProviderInterface::class => \infrastructure\Seo\Form\SeoFormModelProvider::class,
        \domain\Setting\Repository\SettingRepositoryInterface::class => \infrastructure\Setting\Repository\SettingRepository::class,
        \domain\Setting\DataMapper\SettingDataMapperInterface::class => \infrastructure\Setting\DataMapper\SettingDataMapper::class,
        \application\Setting\Form\SettingFormModelProviderInterface::class => \infrastructure\Setting\Form\SettingFormModelProvider::class,
        \domain\MeasurementType\Repository\MeasurementTypeRepositoryInterface::class => \infrastructure\MeasurementType\Repository\MeasurementTypeRepository::class,
        \domain\MeasurementType\DataMapper\MeasurementTypeDataMapperInterface::class => \infrastructure\MeasurementType\DataMapper\MeasurementTypeDataMapper::class,
        \application\MeasurementType\Form\MeasurementTypeFormModelProviderInterface::class => \infrastructure\MeasurementType\Form\MeasurementTypeFormModelProvider::class,
        \domain\Url\Repository\UrlRepositoryInterface::class => \infrastructure\Url\Repository\UrlRepository::class,
        \domain\Url\DataMapper\UrlDataMapperInterface::class => \infrastructure\Url\DataMapper\UrlDataMapper::class,
        \application\Url\Form\UrlFormModelProviderInterface::class => \infrastructure\Url\Form\UrlFormModelProvider::class,
        \application\User\Security\PasswordHasherInterface::class => \infrastructure\User\Security\YiiPasswordHasher::class,
        \application\User\Security\TokenGeneratorInterface::class => \infrastructure\User\Security\YiiTokenGenerator::class,
        \application\User\Security\RoleAssignerInterface::class => \infrastructure\User\Security\YiiRoleAssigner::class,
    ],
];
